# Generated by Django 3.0.7 on 2021-04-29 04:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mensajes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=100)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('asunto', models.CharField(max_length=100)),
                ('mensaje', models.CharField(max_length=100)),
                ('is_answered', models.BooleanField(default=False)),
            ],
        ),
    ]
