# Generated by Django 3.0.7 on 2021-04-29 18:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Demo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('url_pag', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=100)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('url_foto', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='mensajes',
            name='mensaje',
            field=models.TextField(blank=True),
        ),
    ]
